### ISSUE TITLE
Hudson Rock Cybercrime Intelligence Free Integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [x404xx/Breach-Checker#1]
Consider adding Hudson Rock's complimentary data to receive additional intelligence about email address that was compromised in global Infostealer attacks.

Email sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com

Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs

Thank you.

**Comment by x404xx** [comment]
> Consider adding Hudson Rock's complimentary data to receive additional intelligence about email address that was compromised in global Infostealer attacks.
> 
> Email sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com
> 
> Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs
> 
> Thank you.

Thank you. I will try to add these features soon.
